/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing CreatePushTokenInputObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreatePushTokenInputObjectTests
    {
        // TODO uncomment below to declare an instance variable for CreatePushTokenInputObject
        //private CreatePushTokenInputObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreatePushTokenInputObject
            //instance = new CreatePushTokenInputObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreatePushTokenInputObject
        /// </summary>
        [Test]
        public void CreatePushTokenInputObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreatePushTokenInputObject
            //Assert.IsInstanceOfType<CreatePushTokenInputObject> (instance, "variable 'instance' is a CreatePushTokenInputObject");
        }


        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Test]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'PushServiceType'
        /// </summary>
        [Test]
        public void PushServiceTypeTest()
        {
            // TODO unit test for the property 'PushServiceType'
        }

    }

}
