/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing CreateSurveyNodeInputObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateSurveyNodeInputObjectTests
    {
        // TODO uncomment below to declare an instance variable for CreateSurveyNodeInputObject
        //private CreateSurveyNodeInputObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateSurveyNodeInputObject
            //instance = new CreateSurveyNodeInputObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateSurveyNodeInputObject
        /// </summary>
        [Test]
        public void CreateSurveyNodeInputObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateSurveyNodeInputObject
            //Assert.IsInstanceOfType<CreateSurveyNodeInputObject> (instance, "variable 'instance' is a CreateSurveyNodeInputObject");
        }


        /// <summary>
        /// Test the property 'NodeType'
        /// </summary>
        [Test]
        public void NodeTypeTest()
        {
            // TODO unit test for the property 'NodeType'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'StartNode'
        /// </summary>
        [Test]
        public void StartNodeTest()
        {
            // TODO unit test for the property 'StartNode'
        }
        /// <summary>
        /// Test the property 'SendDelay'
        /// </summary>
        [Test]
        public void SendDelayTest()
        {
            // TODO unit test for the property 'SendDelay'
        }

    }

}
