/* 
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing ForwardedCall
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ForwardedCallTests
    {
        // TODO uncomment below to declare an instance variable for ForwardedCall
        //private ForwardedCall instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ForwardedCall
            //instance = new ForwardedCall();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForwardedCall
        /// </summary>
        [Test]
        public void ForwardedCallInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ForwardedCall
            //Assert.IsInstanceOfType<ForwardedCall> (instance, "variable 'instance' is a ForwardedCall");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CallTime'
        /// </summary>
        [Test]
        public void CallTimeTest()
        {
            // TODO unit test for the property 'CallTime'
        }
        /// <summary>
        /// Test the property 'Caller'
        /// </summary>
        [Test]
        public void CallerTest()
        {
            // TODO unit test for the property 'Caller'
        }
        /// <summary>
        /// Test the property 'Via'
        /// </summary>
        [Test]
        public void ViaTest()
        {
            // TODO unit test for the property 'Via'
        }
        /// <summary>
        /// Test the property 'Receiver'
        /// </summary>
        [Test]
        public void ReceiverTest()
        {
            // TODO unit test for the property 'Receiver'
        }

    }

}
