/* 
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing GetOutboundMessagesHistoryResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetOutboundMessagesHistoryResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetOutboundMessagesHistoryResponse
        //private GetOutboundMessagesHistoryResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetOutboundMessagesHistoryResponse
            //instance = new GetOutboundMessagesHistoryResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetOutboundMessagesHistoryResponse
        /// </summary>
        [Test]
        public void GetOutboundMessagesHistoryResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetOutboundMessagesHistoryResponse
            //Assert.IsInstanceOfType<GetOutboundMessagesHistoryResponse> (instance, "variable 'instance' is a GetOutboundMessagesHistoryResponse");
        }


        /// <summary>
        /// Test the property 'LastId'
        /// </summary>
        [Test]
        public void LastIdTest()
        {
            // TODO unit test for the property 'LastId'
        }
        /// <summary>
        /// Test the property 'NextLastId'
        /// </summary>
        [Test]
        public void NextLastIdTest()
        {
            // TODO unit test for the property 'NextLastId'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Test]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }

    }

}
