/* 
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing GroupImage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GroupImageTests
    {
        // TODO uncomment below to declare an instance variable for GroupImage
        //private GroupImage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupImage
            //instance = new GroupImage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupImage
        /// </summary>
        [Test]
        public void GroupImageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupImage
            //Assert.IsInstanceOfType<GroupImage> (instance, "variable 'instance' is a GroupImage");
        }


        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
