/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing ImportColumnMappingItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ImportColumnMappingItemTests
    {
        // TODO uncomment below to declare an instance variable for ImportColumnMappingItem
        //private ImportColumnMappingItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ImportColumnMappingItem
            //instance = new ImportColumnMappingItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ImportColumnMappingItem
        /// </summary>
        [Test]
        public void ImportColumnMappingItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ImportColumnMappingItem
            //Assert.IsInstanceOfType<ImportColumnMappingItem> (instance, "variable 'instance' is a ImportColumnMappingItem");
        }


        /// <summary>
        /// Test the property 'ColumnPositionInFile'
        /// </summary>
        [Test]
        public void ColumnPositionInFileTest()
        {
            // TODO unit test for the property 'ColumnPositionInFile'
        }
        /// <summary>
        /// Test the property 'FieldOrCustomFieldId'
        /// </summary>
        [Test]
        public void FieldOrCustomFieldIdTest()
        {
            // TODO unit test for the property 'FieldOrCustomFieldId'
        }

    }

}
