/* 
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing SuccessfulResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SuccessfulResponseTests
    {
        // TODO uncomment below to declare an instance variable for SuccessfulResponse
        //private SuccessfulResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SuccessfulResponse
            //instance = new SuccessfulResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SuccessfulResponse
        /// </summary>
        [Test]
        public void SuccessfulResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SuccessfulResponse
            //Assert.IsInstanceOfType<SuccessfulResponse> (instance, "variable 'instance' is a SuccessfulResponse");
        }



    }

}
