/* 
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing UpdatePasswordInputObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdatePasswordInputObjectTests
    {
        // TODO uncomment below to declare an instance variable for UpdatePasswordInputObject
        //private UpdatePasswordInputObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdatePasswordInputObject
            //instance = new UpdatePasswordInputObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdatePasswordInputObject
        /// </summary>
        [Test]
        public void UpdatePasswordInputObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdatePasswordInputObject
            //Assert.IsInstanceOfType<UpdatePasswordInputObject> (instance, "variable 'instance' is a UpdatePasswordInputObject");
        }


        /// <summary>
        /// Test the property 'OldPassword'
        /// </summary>
        [Test]
        public void OldPasswordTest()
        {
            // TODO unit test for the property 'OldPassword'
        }
        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Test]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }

    }

}
