/* 
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TextMagicClient.Client.SwaggerDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// CheckPhoneVerificationCodeInputObject1
    /// </summary>
    [DataContract]
    public partial class CheckPhoneVerificationCodeInputObject1 :  IEquatable<CheckPhoneVerificationCodeInputObject1>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckPhoneVerificationCodeInputObject1" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CheckPhoneVerificationCodeInputObject1() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckPhoneVerificationCodeInputObject1" /> class.
        /// </summary>
        /// <param name="code">Verification code that was received by the user and entered into the form field. (required).</param>
        /// <param name="verifyId">VerifyId from Step 1 to match both requests together. (required).</param>
        public CheckPhoneVerificationCodeInputObject1(int? code = default(int?), string verifyId = default(string))
        {
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new InvalidDataException("code is a required property for CheckPhoneVerificationCodeInputObject1 and cannot be null");
            }
            else
            {
                this.Code = code;
            }
            // to ensure "verifyId" is required (not null)
            if (verifyId == null)
            {
                throw new InvalidDataException("verifyId is a required property for CheckPhoneVerificationCodeInputObject1 and cannot be null");
            }
            else
            {
                this.VerifyId = verifyId;
            }
        }
        
        /// <summary>
        /// Verification code that was received by the user and entered into the form field.
        /// </summary>
        /// <value>Verification code that was received by the user and entered into the form field.</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public int? Code { get; set; }

        /// <summary>
        /// VerifyId from Step 1 to match both requests together.
        /// </summary>
        /// <value>VerifyId from Step 1 to match both requests together.</value>
        [DataMember(Name="verifyId", EmitDefaultValue=false)]
        public string VerifyId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CheckPhoneVerificationCodeInputObject1 {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  VerifyId: ").Append(VerifyId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CheckPhoneVerificationCodeInputObject1);
        }

        /// <summary>
        /// Returns true if CheckPhoneVerificationCodeInputObject1 instances are equal
        /// </summary>
        /// <param name="input">Instance of CheckPhoneVerificationCodeInputObject1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CheckPhoneVerificationCodeInputObject1 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.VerifyId == input.VerifyId ||
                    (this.VerifyId != null &&
                    this.VerifyId.Equals(input.VerifyId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.VerifyId != null)
                    hashCode = hashCode * 59 + this.VerifyId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
