/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TextMagicClient.Client.SwaggerDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// UpdateSurveyNodeInputObject
    /// </summary>
    [DataContract]
    public partial class UpdateSurveyNodeInputObject :  IEquatable<UpdateSurveyNodeInputObject>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSurveyNodeInputObject" /> class.
        /// </summary>
        /// <param name="label">Node label.</param>
        /// <param name="isEndNode">Define node is ending for survey. Default is false.</param>
        /// <param name="body">Node body.</param>
        /// <param name="sendDelay">Define delay for sending question to recipients after previous answer..</param>
        public UpdateSurveyNodeInputObject(string label = default(string), bool? isEndNode = default(bool?), string body = default(string), int? sendDelay = default(int?))
        {
            this.Label = label;
            this.IsEndNode = isEndNode;
            this.Body = body;
            this.SendDelay = sendDelay;
        }
        
        /// <summary>
        /// Node label
        /// </summary>
        /// <value>Node label</value>
        [DataMember(Name="label", EmitDefaultValue=false)]
        public string Label { get; set; }

        /// <summary>
        /// Define node is ending for survey. Default is false
        /// </summary>
        /// <value>Define node is ending for survey. Default is false</value>
        [DataMember(Name="isEndNode", EmitDefaultValue=false)]
        public bool? IsEndNode { get; set; }

        /// <summary>
        /// Node body
        /// </summary>
        /// <value>Node body</value>
        [DataMember(Name="body", EmitDefaultValue=false)]
        public string Body { get; set; }

        /// <summary>
        /// Define delay for sending question to recipients after previous answer.
        /// </summary>
        /// <value>Define delay for sending question to recipients after previous answer.</value>
        [DataMember(Name="sendDelay", EmitDefaultValue=false)]
        public int? SendDelay { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateSurveyNodeInputObject {\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  IsEndNode: ").Append(IsEndNode).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  SendDelay: ").Append(SendDelay).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateSurveyNodeInputObject);
        }

        /// <summary>
        /// Returns true if UpdateSurveyNodeInputObject instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateSurveyNodeInputObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateSurveyNodeInputObject input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Label == input.Label ||
                    (this.Label != null &&
                    this.Label.Equals(input.Label))
                ) && 
                (
                    this.IsEndNode == input.IsEndNode ||
                    (this.IsEndNode != null &&
                    this.IsEndNode.Equals(input.IsEndNode))
                ) && 
                (
                    this.Body == input.Body ||
                    (this.Body != null &&
                    this.Body.Equals(input.Body))
                ) && 
                (
                    this.SendDelay == input.SendDelay ||
                    (this.SendDelay != null &&
                    this.SendDelay.Equals(input.SendDelay))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Label != null)
                    hashCode = hashCode * 59 + this.Label.GetHashCode();
                if (this.IsEndNode != null)
                    hashCode = hashCode * 59 + this.IsEndNode.GetHashCode();
                if (this.Body != null)
                    hashCode = hashCode * 59 + this.Body.GetHashCode();
                if (this.SendDelay != null)
                    hashCode = hashCode * 59 + this.SendDelay.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
